import json,pathlib,html
p=pathlib.Path('docs/icon-pilot');e=html.escape
manifest=json.loads((p/'SILHOUETTE-SET-MANIFEST.json').read_text());inventory=json.loads((p/'KEY-RISK-CORRECTED-INVENTORY.json').read_text());before=json.loads((p/'KEY-RISK-ASSIGNMENTS-INVENTORY.json').read_text());prior={x['key']:x for x in before['crops']};proofs=json.loads((p/'KEY-RISK-CORRECTION-PROOFS.json').read_text())
labels={'leaf_mould':'Leaf and stalk mould','perennial_root_decay':'Perennial root decay','pepper_end_rot':'Pepper end rot','leafy_heart_rot':'Rotting leafy heart','courgette_abort':'Failed courgette fruit set','courgette_rot':'Courgette fruit rot','cucumber_slice':'Bitter cucumber','fennel_small':'Small fennel bulbs','fennel_base_rot':'Fennel lower-sheath rot','allium_base_rot':'Allium white rot','lifted_clove':'Lifted garlic cloves','kohlrabi_fibrous':'Woody kohlrabi','mushroom_mould':'Contaminating moulds','mushroom_sparse':'Poor mushroom cropping','parsnip_canker':'Parsnip canker','potato_scab':'Potato scab','cyst_roots':'Potato cyst eelworm','fibrous_root':'Fibrous root quality','stunted_root':'Checked root growth','rhubarb_crown':'Rhubarb crown rot','rhubarb_thin_stalk':'Thin rhubarb stalks','honey_fungus_root':'Honey fungus','white_blister_leaf':'White blister','broken_long_root':'Snapped long roots','squash_stalk_rot':'Squash stalk damage','corn_missing_kernels':'Poor maize pollination','corn_pollen':'Maize cross-pollination','split_tomato':'Split tomato','downy_mildew_leaf':'Downy mildew','beet_heart_rot':'Beetroot heart rot','cauliflower_button':'Button cauliflowers'}
uses={i['png']:[] for i in manifest['icons']}
for c in inventory['crops']:
 for r in c['risks']:
  if r['icon'] in uses:uses[r['icon']].append(c['name'])
art=''
for i in manifest['icons']:
 approved=i['key'] in manifest['approved_references'];art+=f'<article class="art"><small>{"Approved reference" if approved else ("Approved" if i.get("status")=="approved by John" else "Redrawn · for review")}</small><h3>{e(labels[i["key"]])}</h3><img class="large" src="../../public{i["png"]}" alt="{e(labels[i["key"]])}"><div class="actual"><img src="../../public{i["png"]}" alt=""><span>32px</span></div><p>{e(" · ".join(uses[i["png"]]))}</p><a href="../../public{i["png"]}">Transparent PNG</a></article>'
def strip(c):
 parts=[]
 for r in c['risks']:
  image=f'<img src="../../public{r["icon"]}">' if r['icon'] else '<span style="display:block;height:40px">—</span>'
  parts.append(f'<div>{image}<b>{e(r["label"])}</b><p>{e(r["text"])}</p></div>')
 return '<div class="strip">'+''.join(parts)+'</div>'

changes=[];sections=''
for c in inventory['crops']:
 if c['risks']==prior[c['key']]['risks']:continue
 changes.append(c['key']);sections+=f'<article class="crop"><h3>{e(c["name"])}</h3><small>Previous</small>{strip(prior[c["key"]])}<small>Corrected</small>{strip(c)}</article>'
links=''
for crop in dict.fromkeys(r['crop'] for r in proofs['results']):
 row=[r for r in proofs['results'] if r['crop']==crop];name=next(c['name'] for c in inventory['crops'] if c['key']==crop);links+=f'<li><b>{e(name)}</b> — '+ ' · '.join(f'<a href="../../{r["file"]}">{r["units"]} PDF</a>' for r in row)+'</li>'
text=f'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Key Risks — silhouette redraws</title><style>
*{{box-sizing:border-box}}body{{font:16px/1.45 system-ui;background:#f4f5ef;color:#303c32;margin:auto;max-width:1240px;padding:30px 22px}}h1{{margin:0;font-size:30px}}h2{{font-size:24px}}h3{{font-size:17px;margin:8px 0}}small{{font-size:11px;letter-spacing:.09em;text-transform:uppercase;color:#61705c}}a{{color:#286546}}nav{{display:flex;gap:20px;flex-wrap:wrap;margin:22px 0}}.notice{{padding:15px;background:#e6eedf;border-radius:8px}}.gallery{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px}}article{{border:1px solid #d0d8ca;background:#fffefa;border-radius:10px;padding:18px}}.art{{text-align:center}}img{{object-fit:contain;filter:url(#ink)}}.large{{display:block;width:128px;height:128px;margin:14px auto}}.actual{{display:flex;align-items:center;justify-content:center;gap:14px;background:#f0f5e9;border-radius:6px;padding:10px}}.actual img{{width:32px;height:32px}}.actual span{{font-size:12px;color:#61705c}}.art p{{font-size:12px;min-height:35px}}.art a{{font-size:12px}}.crop{{margin:18px 0}}.strip{{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));background:#f6f9f2;border:1px solid #c6d4c0;border-radius:6px;margin:7px 0 18px;padding:8px 0}}.strip>div{{padding:8px 12px;text-align:center;border-right:1px solid #d7e0d0}}.strip>div:last-child{{border:0}}.strip img{{display:block;width:32px;height:32px;margin:0 auto 8px}}.strip b{{font-size:12px;display:block}}.strip p{{font-size:12px;line-height:1.25;margin:4px 0}}li{{margin:10px 0}}summary{{font-size:22px;font-weight:650;cursor:pointer;margin-top:30px}}@media(max-width:850px){{.gallery{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}@media(max-width:500px){{body{{padding:20px 12px}}.gallery{{gap:9px}}article{{padding:12px 8px}}.large{{width:110px;height:110px}}.strip{{grid-template-columns:repeat(2,minmax(0,1fr))}}h1{{font-size:25px}}}}
</style><svg width="0" height="0" aria-hidden="true" style="position:absolute"><defs><filter id="ink" color-interpolation-filters="sRGB"><feFlood flood-color="#30352f"/><feComposite in2="SourceAlpha" operator="in"/></filter></defs></svg><small>Key Risks · solid silhouettes · 24 September</small><h1>The approved silhouette set</h1><p>29 redraws alongside the two approved pepper and potato references. Each is shown enlarged and at the actual 32px size.</p><div class="notice">All 44 vegetable strips checked: 173 cards with images, no duplicate condition identities. Core data and existing print selections preserved during this redraw. All drawings and these page proofs were approved by John on 24 September.</div><nav><a href="#artwork">Drawings</a><a href="#proofs">Page proofs</a><a href="#assignments">Crop assignments</a><a href="SILHOUETTE-PROOFS.html">Approved style references</a></nav><h2 id="artwork">Drawings</h2><div class="gallery">{art}</div><h2 id="proofs">Representative page proofs</h2><p>Five vegetables, both units; individual two-page A4 files.</p><ul>{links}</ul><details id="assignments"><summary>Corrected strips — {len(changes)} vegetables</summary><p>Earlier approved images compared with the corrected assignments. Newly exposed conditions replace duplicate cards.</p>{sections}</details><p><a href="SILHOUETTE-ASSIGNMENT-CHECKS.json">Assignment checks</a> · <a href="KEY-RISK-CORE-RECEIPT.json">Earlier core-data correction receipt</a></p></html>'''
(p/'SILHOUETTE-SET.html').write_text(text);print(len(manifest['icons']),'drawings;',len(changes),'changed crops')
